
export enum ConfigsEnum {
  APP_NAME = 'APP_NAME',
  APP_HOST = 'APP_HOST',
  APP_PORT = 'APP_PORT',
  APP_URL = 'APP_URL',
  APP_KEY = 'APP_KEY',
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_DBNAME = 'MYSQL_DBNAME',
  SYSTEM_TOKEN = 'SYSTEM_TOKEN',
} 